baseURL: "https://vdbogdanov.ru/"
languageCode: "en-us"
title: "üßôüèº‚Äç‚ôÇÔ∏è[vdbogdanov@site]"
theme: "PaperMod"
googleAnalytics: "G-NMWZKMRJWX"

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  ShowBreadCrumbs: true
  ShowReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - "title"
      - "permalink"
      - "summary"
      - "content"

  homeInfoParams:
    Title: "–ü—Ä–∏–≤–µ—Ç ü§ó"
    Content: "–ú–µ–Ω—è –∑–æ–≤—É—Ç –ë–æ–≥–¥–∞–Ω–æ–≤ –í–ª–∞–¥–∏–º–∏—Ä, —è —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫ / linux-–∏–Ω–∂–µ–Ω–µ—Ä. –ó–∞–Ω–∏–º–∞—é—Å—å —Å–æ–∑–¥–∞–Ω–∏–µ–º —Ä–∞–∑–ª–∏—á–Ω—ã—Ö –ø—Ä–æ–µ–∫—Ç–æ–≤, —Å–ø–µ—Ü–∏–∞–ª–∏–∑–∏—Ä—É—è—Å—å –Ω–∞ –∞–≤—Ç–æ–º–∞—Ç–∏–∑–∞—Ü–∏–∏ –∏–Ω—Ñ—Ä–∞—Å—Ç—Ä—É–∫—Ç—É—Ä–Ω—ã—Ö –∑–∞–¥–∞—á. –°–µ–π—á–∞—Å —è –ø–æ–≥—Ä—É–∂–∞—é—Å—å –≤ —Ç–µ—Ö–Ω–æ–ª–æ–≥–∏—á–µ—Å–∫–∏–π —Å—Ç–µ–∫ DevOps, –ø–æ—ç—Ç–æ–º—É –≤ –±–ª–∏–∂–∞–π—à–µ–µ –≤—Ä–µ–º—è –∑–¥–µ—Å—å –ø–æ—è–≤–∏—Ç—Å—è –º–Ω–æ–≥–æ –∏–Ω—Ç–µ—Ä–µ—Å–Ω–æ–≥–æ –º–∞—Ç–µ—Ä–∏–∞–ª–∞..."

  socialIcons:
    - name: Github
      url: "https://github.com/vdbogdanov"
    - name: Telegram
      url: "https://t.me/vdbogdanov"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/vdbogdanov/"

  assets:
    favicon: "/favicons/favicon.ico"
    favicon16x16: "/favicons/favicon-16x16.png"
    favicon32x32: "/favicons/favicon-32x32.png"
    apple_touch_icon: "/favicons/apple-touch-icon.png"

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 30
    - identifier: search
      name: Search
      pageref: /search
      weight: 40
